// Package db_model contains generated code for schema 'sportsday'.
package db_model

// Code generated by xo. DO NOT EDIT.

// AdminArbitration represents a row from 'sportsday.admin_arbitrations'.
type AdminArbitration struct {
	ID       string `json:"id"`        // id
	LeagueID string `json:"league_id"` // league_id
	Status   Status `json:"status"`    // status
}
