package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// AdminArbitrationEntry represents a row from 'sportsday.admin_arbitration_entries'.
type AdminArbitrationEntry struct {
	ID            string        `json:"id"`             // id
	ArbitrationID string        `json:"arbitration_id"` // arbitration_id
	TeamID        string        `json:"team_id"`        // team_id
	ResolvedRank  sql.NullInt64 `json:"resolved_rank"`  // NULL=未裁定, NOT NULL=裁定済みの絶対順位
}
