package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// AdminArbitrationEntry represents a row from 'sportsday.admin_arbitration_entries'.
type AdminArbitrationEntry struct {
	ID            string        `json:"id"`             // ID
	ArbitrationID string        `json:"arbitration_id"` // 裁定ID
	TeamID        string        `json:"team_id"`        // チームID
	ResolvedRank  sql.NullInt64 `json:"resolved_rank"`  // 裁定順位
}
