// Package db_model contains generated code for schema 'sportsday'.
package db_model

// Code generated by xo. DO NOT EDIT.

// AdminArbitration represents a row from 'sportsday.admin_arbitrations'.
type AdminArbitration struct {
	ID       string `json:"id"`        // ID
	LeagueID string `json:"league_id"` // リーグID
	Status   string `json:"status"`    // 状態
}
