// Package db_model contains generated code for schema 'sportsday'.
package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// Competition represents a row from 'sportsday.competitions'.
type Competition struct {
	ID                string         `json:"id"`                  // 主キー
	Name              string         `json:"name"`                // 大会名
	Type              string         `json:"type"`                // 大会種別
	DefaultLocationID sql.NullString `json:"default_location_id"` // 既定の会場
}
