package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql/driver"
	"fmt"
)

// ConditionKey is the 'condition_key' enum type from schema 'sportsday'.
type ConditionKey uint16

// ConditionKey values.
const (
	// ConditionKeyWinPoints is the 'WIN_POINTS' condition_key.
	ConditionKeyWinPoints ConditionKey = 1
	// ConditionKeyGoalDiff is the 'GOAL_DIFF' condition_key.
	ConditionKeyGoalDiff ConditionKey = 2
	// ConditionKeyTotalGoals is the 'TOTAL_GOALS' condition_key.
	ConditionKeyTotalGoals ConditionKey = 3
	// ConditionKeyHeadToHead is the 'HEAD_TO_HEAD' condition_key.
	ConditionKeyHeadToHead ConditionKey = 4
	// ConditionKeyAdminDecision is the 'ADMIN_DECISION' condition_key.
	ConditionKeyAdminDecision ConditionKey = 5
)

// String satisfies the [fmt.Stringer] interface.
func (ck ConditionKey) String() string {
	switch ck {
	case ConditionKeyWinPoints:
		return "WIN_POINTS"
	case ConditionKeyGoalDiff:
		return "GOAL_DIFF"
	case ConditionKeyTotalGoals:
		return "TOTAL_GOALS"
	case ConditionKeyHeadToHead:
		return "HEAD_TO_HEAD"
	case ConditionKeyAdminDecision:
		return "ADMIN_DECISION"
	}
	return fmt.Sprintf("ConditionKey(%d)", ck)
}

// MarshalText marshals [ConditionKey] into text.
func (ck ConditionKey) MarshalText() ([]byte, error) {
	return []byte(ck.String()), nil
}

// UnmarshalText unmarshals [ConditionKey] from text.
func (ck *ConditionKey) UnmarshalText(buf []byte) error {
	switch str := string(buf); str {
	case "WIN_POINTS":
		*ck = ConditionKeyWinPoints
	case "GOAL_DIFF":
		*ck = ConditionKeyGoalDiff
	case "TOTAL_GOALS":
		*ck = ConditionKeyTotalGoals
	case "HEAD_TO_HEAD":
		*ck = ConditionKeyHeadToHead
	case "ADMIN_DECISION":
		*ck = ConditionKeyAdminDecision
	default:
		return ErrInvalidConditionKey(str)
	}
	return nil
}

// Value satisfies the [driver.Valuer] interface.
func (ck ConditionKey) Value() (driver.Value, error) {
	return ck.String(), nil
}

// Scan satisfies the [sql.Scanner] interface.
func (ck *ConditionKey) Scan(v interface{}) error {
	switch x := v.(type) {
	case []byte:
		return ck.UnmarshalText(x)
	case string:
		return ck.UnmarshalText([]byte(x))
	}
	return ErrInvalidConditionKey(fmt.Sprintf("%T", v))
}

// NullConditionKey represents a null 'condition_key' enum for schema 'sportsday'.
type NullConditionKey struct {
	ConditionKey ConditionKey
	// Valid is true if [ConditionKey] is not null.
	Valid bool
}

// Value satisfies the [driver.Valuer] interface.
func (nck NullConditionKey) Value() (driver.Value, error) {
	if !nck.Valid {
		return nil, nil
	}
	return nck.ConditionKey.Value()
}

// Scan satisfies the [sql.Scanner] interface.
func (nck *NullConditionKey) Scan(v interface{}) error {
	if v == nil {
		nck.ConditionKey, nck.Valid = 0, false
		return nil
	}
	err := nck.ConditionKey.Scan(v)
	nck.Valid = err == nil
	return err
}

// ErrInvalidConditionKey is the invalid [ConditionKey] error.
type ErrInvalidConditionKey string

// Error satisfies the error interface.
func (err ErrInvalidConditionKey) Error() string {
	return fmt.Sprintf("invalid ConditionKey(%s)", string(err))
}
