package db_model

// Code generated by xo. DO NOT EDIT.

// Image represents a row from 'sportsday.images'.
type Image struct {
	ID          string `json:"id"`           // id
	ObjectKey   string `json:"object_key"`   // object_key
	OwnerType   string `json:"owner_type"`   // owner_type
	OwnerID     string `json:"owner_id"`     // owner_id
	ContentType string `json:"content_type"` // content_type
}
