package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// Image represents a row from 'sportsday.images'.
type Image struct {
	ID         string         `json:"id"`          // image id
	Status     string         `json:"status"`      // status
	URL        sql.NullString `json:"url"`         // url
	UploadedAt sql.NullTime   `json:"uploaded_at"` // uploaded_at
}
