package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// Information represents a row from 'sportsday.information'.
type Information struct {
	ID          string       `json:"id"`           // ID
	Title       string       `json:"title"`        // タイトル
	Content     string       `json:"content"`      // コメント
	Status      string       `json:"status"`       // ステータス
	ScheduledAt sql.NullTime `json:"scheduled_at"` // 公開予約日時
}
