package db_model

// Code generated by xo. DO NOT EDIT.

// MatchEntry represents a row from 'sportsday.match_entries'.
type MatchEntry struct {
	MatchID string `json:"match_id"` // 試合ID
	TeamID  string `json:"team_id"`  // チームID
	Score   int    `json:"score"`    // 点数
}
