package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// PromotionRule represents a row from 'sportsday.promotion_rules'.
type PromotionRule struct {
	ID                  string        `json:"id"`                    // ID
	SourceCompetitionID string        `json:"source_competition_id"` // 進出元大会ID
	TargetCompetitionID string        `json:"target_competition_id"` // 進出先大会ID
	RankSpec            string        `json:"rank_spec"`             // 進出対象順位
	SlotStart           sql.NullInt64 `json:"slot_start"`            // スロット開始位置
}
