package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// PromotionRule represents a row from 'sportsday.promotion_rules'.
type PromotionRule struct {
	ID                  string        `json:"id"`                    // 主キー
	SourceCompetitionID string        `json:"source_competition_id"` // 進出元の大会ID
	TargetCompetitionID string        `json:"target_competition_id"` // 進出先の大会ID
	RankSpec            string        `json:"rank_spec"`             // 進出対象順位
	Slot                sql.NullInt64 `json:"slot"`                  // スロット位置
}
