package db_model

// Code generated by xo. DO NOT EDIT.

// RankingRule represents a row from 'sportsday.ranking_rules'.
type RankingRule struct {
	ID           string       `json:"id"`            // id
	LeagueID     string       `json:"league_id"`     // league_id
	ConditionKey ConditionKey `json:"condition_key"` // condition_key
	Priority     int          `json:"priority"`      // 1始まり、小さい値ほど優先順位が高い
}
