package db_model

// Code generated by xo. DO NOT EDIT.

// RankingRule represents a row from 'sportsday.ranking_rules'.
type RankingRule struct {
	ID           string `json:"id"`            // ID
	LeagueID     string `json:"league_id"`     // リーグID
	ConditionKey string `json:"condition_key"` // 条件キー
	Priority     int    `json:"priority"`      // 優先順位
}
