package db_model

// Code generated by xo. DO NOT EDIT.

// RankingRule represents a row from 'sportsday.ranking_rules'.
type RankingRule struct {
	SportID      string `json:"sport_id"`      // 競技ID
	ConditionKey string `json:"condition_key"` // 条件キー
	Priority     int    `json:"priority"`      // 優先順位
}
