package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// Rule represents a row from 'sportsday.rules'.
type Rule struct {
	ID      string         `json:"id"`       // ID
	Rule    string         `json:"rule"`     // ルール
	SportID sql.NullString `json:"sport_id"` // 競技ID
}
