package db_model

// Code generated by xo. DO NOT EDIT.

// Scene represents a row from 'sportsday.scenes'.
type Scene struct {
	ID           string `json:"id"`            // ID
	Name         string `json:"name"`          // シーン名
	DisplayOrder int    `json:"display_order"` // 表示順
	IsDeleted    bool   `json:"is_deleted"`    // 論理削除フラグ
}
