package db_model

// Code generated by xo. DO NOT EDIT.

// SportExperience represents a row from 'sportsday.sport_experiences'.
type SportExperience struct {
	UserID  string `json:"user_id"`  // ユーザーID
	SportID string `json:"sport_id"` // スポーツID
}
