package db_model

// Code generated by xo. DO NOT EDIT.

// SportEntry represents a row from 'sportsday.sport_entries'.
type SportEntry struct {
	ID           string `json:"id"`             // id
	SportSceneID string `json:"sport_scene_id"` // スポーツとシーンの中間テーブルID
	TeamID       string `json:"team_id"`        // チームID
}
