package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// Sport represents a row from 'sportsday.sports'.
type Sport struct {
	ID               string         `json:"id"`                // ID
	Name             string         `json:"name"`              // スポーツ名
	DisplayOrder     int            `json:"display_order"`     // 表示順
	ImageID          sql.NullString `json:"image_id"`          // image_id
	ExperiencedLimit sql.NullInt64  `json:"experienced_limit"` // 経験者上限
}
