package db_model

// Code generated by xo. DO NOT EDIT.

// SportScene represents a row from 'sportsday.sport_scene'.
type SportScene struct {
	ID      string `json:"id"`       // id
	SceneID string `json:"scene_id"` // シーンID
	SportID string `json:"sport_id"` // スポーツID
}
