package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql/driver"
	"fmt"
)

// Status is the 'status' enum type from schema 'sportsday'.
type Status uint16

// Status values.
const (
	// StatusPending is the 'PENDING' status.
	StatusPending Status = 1
	// StatusResolved is the 'RESOLVED' status.
	StatusResolved Status = 2
)

// String satisfies the [fmt.Stringer] interface.
func (s Status) String() string {
	switch s {
	case StatusPending:
		return "PENDING"
	case StatusResolved:
		return "RESOLVED"
	}
	return fmt.Sprintf("Status(%d)", s)
}

// MarshalText marshals [Status] into text.
func (s Status) MarshalText() ([]byte, error) {
	return []byte(s.String()), nil
}

// UnmarshalText unmarshals [Status] from text.
func (s *Status) UnmarshalText(buf []byte) error {
	switch str := string(buf); str {
	case "PENDING":
		*s = StatusPending
	case "RESOLVED":
		*s = StatusResolved
	default:
		return ErrInvalidStatus(str)
	}
	return nil
}

// Value satisfies the [driver.Valuer] interface.
func (s Status) Value() (driver.Value, error) {
	return s.String(), nil
}

// Scan satisfies the [sql.Scanner] interface.
func (s *Status) Scan(v interface{}) error {
	switch x := v.(type) {
	case []byte:
		return s.UnmarshalText(x)
	case string:
		return s.UnmarshalText([]byte(x))
	}
	return ErrInvalidStatus(fmt.Sprintf("%T", v))
}

// NullStatus represents a null 'status' enum for schema 'sportsday'.
type NullStatus struct {
	Status Status
	// Valid is true if [Status] is not null.
	Valid bool
}

// Value satisfies the [driver.Valuer] interface.
func (ns NullStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return ns.Status.Value()
}

// Scan satisfies the [sql.Scanner] interface.
func (ns *NullStatus) Scan(v interface{}) error {
	if v == nil {
		ns.Status, ns.Valid = 0, false
		return nil
	}
	err := ns.Status.Scan(v)
	ns.Valid = err == nil
	return err
}

// ErrInvalidStatus is the invalid [Status] error.
type ErrInvalidStatus string

// Error satisfies the error interface.
func (err ErrInvalidStatus) Error() string {
	return fmt.Sprintf("invalid Status(%s)", string(err))
}
