package db_model

// Code generated by xo. DO NOT EDIT.

// TiebreakPriority represents a row from 'sportsday.tiebreak_priorities'.
type TiebreakPriority struct {
	LeagueID string `json:"league_id"` // リーグID
	TeamID   string `json:"team_id"`   // チームID
	Priority int    `json:"priority"`  // 同順位チーム内での優先度
}
