package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// Tournament represents a row from 'sportsday.tournaments'.
type Tournament struct {
	ID              string         `json:"id"`               // ID
	CompetitionID   string         `json:"competition_id"`   // 大会ID
	Name            string         `json:"name"`             // ブラケット名
	BracketType     string         `json:"bracket_type"`     // ブラケット種別
	PlacementMethod sql.NullString `json:"placement_method"` // 配置方式
	DisplayOrder    int            `json:"display_order"`    // 表示順
}
