package db_model

// Code generated by xo. DO NOT EDIT.

// Tournament represents a row from 'sportsday.tournaments'.
type Tournament struct {
	ID            string `json:"id"`             // ID
	CompetitionID string `json:"competition_id"` // 所属する大会ID
	Name          string `json:"name"`           // ブラケット名
	BracketType   string `json:"bracket_type"`   // ブラケット種別
	DisplayOrder  int    `json:"display_order"`  // UI上の表示順
}
