package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// TournamentSlot represents a row from 'sportsday.tournament_slots'.
type TournamentSlot struct {
	ID            string         `json:"id"`              // ID
	TournamentID  string         `json:"tournament_id"`   // ブラケットID
	MatchEntryID  string         `json:"match_entry_id"`  // 対応するmatch_entries.id
	SlotPosition  int8           `json:"slot_position"`   // スロット位置 (1 or 2)
	SourceType    string         `json:"source_type"`     // ソース種別
	SourceMatchID sql.NullString `json:"source_match_id"` // ソース試合ID
	SeedNumber    sql.NullInt32  `json:"seed_number"`     // シード番号 (SEED時)
}
