package db_model

// Code generated by xo. DO NOT EDIT.

// UserRole represents a row from 'sportsday.user_roles'.
type UserRole struct {
	Sub  string `json:"sub"`  // JWT sub claim（IdP識別子）
	Role string `json:"role"` // ロール識別子（admin / organizer / participant）
}
