package db_model

// Code generated by xo. DO NOT EDIT.

// UserRole represents a row from 'sportsday.user_roles'.
type UserRole struct {
	UserID string `json:"user_id"` // usersテーブルのID
	Role   string `json:"role"`    // ロール識別子（admin / organizer / participant）
}
