package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// UsersIdp represents a row from 'sportsday.users_idps'.
type UsersIdp struct {
	UserID          string         `json:"user_id"`           // User ID
	Provider        string         `json:"provider"`          // プロバイダー名
	Sub             sql.NullString `json:"sub"`               // OIDCユーザーの識別子
	MicrosoftUserID sql.NullString `json:"microsoft_user_id"` // MicrosoftにおけるユーザーID(JWT oid)
	GoogleUserID    sql.NullString `json:"google_user_id"`    // GoogleにおけるユーザーID
}
