package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// User represents a row from 'sportsday.users'.
type User struct {
	ID    string         `json:"id"`    // ID
	Name  sql.NullString `json:"name"`  // ユーザ名
	Email sql.NullString `json:"email"` // メールアドレス
}
