services:
  app:
    image: mcr.microsoft.com/devcontainers/base:jammy
    init: true
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
  mysql:
    image: mysql:8
    container_name: sports-day-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sportsday
    volumes:
      - mysql_data:/var/lib/mysql
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8888:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    command:
      - start-dev
volumes:
  mysql_data:
  keycloak_data:
