// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type AuthResponse struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type CreateCompetitionInput struct {
	Name string          `json:"name"`
	Type CompetitionType `json:"type"`
}

type CreateGroupInput struct {
	Name string `json:"name"`
}

type CreateInformationInput struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type CreateJudgmentInput struct {
	ID    string         `json:"id"`
	Entry *JudgmentEntry `json:"entry"`
}

type CreateLeagueInput struct {
	Name              string  `json:"name"`
	DefaultLocationID *string `json:"defaultLocationId,omitempty"`
}

type CreateLocationInput struct {
	Name string `json:"name"`
}

type CreateMatchInput struct {
	Time          string         `json:"time"`
	Status        MatchStatus    `json:"status"`
	LocationID    *string        `json:"locationId,omitempty"`
	CompetitionID string         `json:"competitionId"`
	TeamIds       []string       `json:"teamIds,omitempty"`
	Judgment      *JudgmentEntry `json:"judgment,omitempty"`
}

type CreatePromotionRuleInput struct {
	SourceCompetitionID string `json:"sourceCompetitionId"`
	TargetCompetitionID string `json:"targetCompetitionId"`
	RankSpec            string `json:"rankSpec"`
	Slot                *int32 `json:"slot,omitempty"`
}

type CreateSceneInput struct {
	Name string `json:"name"`
}

type CreateSportsInput struct {
	Name string `json:"name"`
}

type CreateTeamInput struct {
	Name    string   `json:"name"`
	GroupID string   `json:"groupId"`
	UserIds []string `json:"userIds"`
}

type CreateUserInput struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type GenerateRoundRobinInput struct {
	StartTime     string  `json:"startTime"`
	MatchDuration int32   `json:"matchDuration"`
	BreakDuration int32   `json:"breakDuration"`
	LocationID    *string `json:"locationId,omitempty"`
}

type Information struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

// 3 つの ID のうち **ちょうど 1 つだけ** を非 NULL にしてください。
// 1 つも指定しない、または 2 つ以上同時に指定した場合、サーバーは BAD_REQUEST を返します。
type JudgmentEntry struct {
	Name    *string `json:"name,omitempty"`
	UserID  *string `json:"userId,omitempty"`
	TeamID  *string `json:"teamId,omitempty"`
	GroupID *string `json:"groupId,omitempty"`
}

type LoginInput struct {
	Code        string `json:"code"`
	RedirectURL string `json:"redirectURL"`
}

type MatchEntry struct {
	ID    string `json:"id"`
	Team  *Team  `json:"team,omitempty"`
	Score int32  `json:"score"`
}

type MatchResultInput struct {
	TeamID string `json:"teamId"`
	Score  int32  `json:"score"`
}

type Mutation struct {
}

type PromotionRule struct {
	ID                string       `json:"id"`
	SourceCompetition *Competition `json:"sourceCompetition"`
	TargetCompetition *Competition `json:"targetCompetition"`
	RankSpec          string       `json:"rankSpec"`
	Slot              *int32       `json:"slot,omitempty"`
}

type PromotionStatus struct {
	TargetCompetitionID string `json:"targetCompetitionId"`
	ExpectedTeamCount   int32  `json:"expectedTeamCount"`
	CurrentEntryCount   int32  `json:"currentEntryCount"`
}

type Query struct {
}

type RankingRule struct {
	ConditionKey RankingConditionKey `json:"conditionKey"`
	Priority     int32               `json:"priority"`
}

type RankingRuleInput struct {
	ConditionKey RankingConditionKey `json:"conditionKey"`
	Priority     int32               `json:"priority"`
}

type Scene struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Sport struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Weight       int32          `json:"weight"`
	RankingRules []*RankingRule `json:"rankingRules"`
}

type TiebreakPriority struct {
	Team     *Team `json:"team"`
	Priority int32 `json:"priority"`
}

type TiebreakPriorityInput struct {
	TeamID   string `json:"teamId"`
	Priority int32  `json:"priority"`
}

type UpdateCompetitionEntriesInput struct {
	TeamIds []string `json:"teamIds"`
}

type UpdateCompetitionInput struct {
	Name *string `json:"name,omitempty"`
}

type UpdateGroupInput struct {
	Name *string `json:"name,omitempty"`
}

type UpdateGroupUsersInput struct {
	UserIds []string `json:"userIds"`
}

type UpdateInformationInput struct {
	Title   *string `json:"title,omitempty"`
	Content *string `json:"content,omitempty"`
}

type UpdateJudgmentInput struct {
	Entry *JudgmentEntry `json:"entry,omitempty"`
}

type UpdateLeagueRuleInput struct {
	WinPt  *int32 `json:"winPt,omitempty"`
	DrawPt *int32 `json:"drawPt,omitempty"`
	LosePt *int32 `json:"losePt,omitempty"`
}

type UpdateLocationInput struct {
	Name *string `json:"name,omitempty"`
}

type UpdateMatchDetailInput struct {
	Time       *string `json:"time,omitempty"`
	LocationID *string `json:"locationId,omitempty"`
}

type UpdateMatchEntriesInput struct {
	TeamIds []string `json:"teamIds"`
}

type UpdateMatchEntryScoreInput struct {
	TeamID string `json:"teamId"`
	Score  int32  `json:"score"`
}

type UpdateMatchResultInput struct {
	Status       *MatchStatus        `json:"status,omitempty"`
	WinnerTeamID *string             `json:"winnerTeamId,omitempty"`
	Results      []*MatchResultInput `json:"results,omitempty"`
}

type UpdatePromotionRuleInput struct {
	RankSpec *string `json:"rankSpec,omitempty"`
	Slot     *int32  `json:"slot,omitempty"`
}

type UpdateSceneInput struct {
	Name *string `json:"name,omitempty"`
}

type UpdateSportsInput struct {
	Name   *string `json:"name,omitempty"`
	Weight *int32  `json:"weight,omitempty"`
}

type UpdateTeamInput struct {
	Name    *string `json:"name,omitempty"`
	GroupID *string `json:"groupId,omitempty"`
}

type UpdateTeamUsersInput struct {
	AddUserIds    []string `json:"addUserIds,omitempty"`
	RemoveUserIds []string `json:"removeUserIds,omitempty"`
}

type CompetitionType string

const (
	CompetitionTypeLeague     CompetitionType = "LEAGUE"
	CompetitionTypeTournament CompetitionType = "TOURNAMENT"
)

var AllCompetitionType = []CompetitionType{
	CompetitionTypeLeague,
	CompetitionTypeTournament,
}

func (e CompetitionType) IsValid() bool {
	switch e {
	case CompetitionTypeLeague, CompetitionTypeTournament:
		return true
	}
	return false
}

func (e CompetitionType) String() string {
	return string(e)
}

func (e *CompetitionType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CompetitionType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CompetitionType", str)
	}
	return nil
}

func (e CompetitionType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type MatchStatus string

const (
	MatchStatusCanceled MatchStatus = "CANCELED"
	MatchStatusStandby  MatchStatus = "STANDBY"
	MatchStatusOngoing  MatchStatus = "ONGOING"
	MatchStatusFinished MatchStatus = "FINISHED"
)

var AllMatchStatus = []MatchStatus{
	MatchStatusCanceled,
	MatchStatusStandby,
	MatchStatusOngoing,
	MatchStatusFinished,
}

func (e MatchStatus) IsValid() bool {
	switch e {
	case MatchStatusCanceled, MatchStatusStandby, MatchStatusOngoing, MatchStatusFinished:
		return true
	}
	return false
}

func (e MatchStatus) String() string {
	return string(e)
}

func (e *MatchStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MatchStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MatchStatus", str)
	}
	return nil
}

func (e MatchStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type RankingConditionKey string

const (
	RankingConditionKeyWinPoints     RankingConditionKey = "WIN_POINTS"
	RankingConditionKeyGoalDiff      RankingConditionKey = "GOAL_DIFF"
	RankingConditionKeyTotalGoals    RankingConditionKey = "TOTAL_GOALS"
	RankingConditionKeyHeadToHead    RankingConditionKey = "HEAD_TO_HEAD"
	RankingConditionKeyAdminDecision RankingConditionKey = "ADMIN_DECISION"
)

var AllRankingConditionKey = []RankingConditionKey{
	RankingConditionKeyWinPoints,
	RankingConditionKeyGoalDiff,
	RankingConditionKeyTotalGoals,
	RankingConditionKeyHeadToHead,
	RankingConditionKeyAdminDecision,
}

func (e RankingConditionKey) IsValid() bool {
	switch e {
	case RankingConditionKeyWinPoints, RankingConditionKeyGoalDiff, RankingConditionKeyTotalGoals, RankingConditionKeyHeadToHead, RankingConditionKeyAdminDecision:
		return true
	}
	return false
}

func (e RankingConditionKey) String() string {
	return string(e)
}

func (e *RankingConditionKey) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RankingConditionKey(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RankingConditionKey", str)
	}
	return nil
}

func (e RankingConditionKey) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
